// <auto-generated />
using System;
using JewelleryApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JewelleryApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260427061006_AddTodayRateToVoucher")]
    partial class AddTodayRateToVoucher
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.15");

            modelBuilder.Entity("JewelleryApp.Models.Jewellery.AccountGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSubLedger")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PositionInHierarchy")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentGroupId");

                    b.ToTable("AccountGroups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 1,
                            IsSubLedger = false,
                            Name = "ASSETS",
                            PositionInHierarchy = 1
                        },
                        new
                        {
                            Id = 2,
                            Category = 2,
                            IsSubLedger = false,
                            Name = "LIABILITIES",
                            PositionInHierarchy = 1
                        },
                        new
                        {
                            Id = 3,
                            Category = 3,
                            IsSubLedger = false,
                            Name = "INCOME",
                            PositionInHierarchy = 1
                        },
                        new
                        {
                            Id = 4,
                            Category = 4,
                            IsSubLedger = false,
                            Name = "EXPENDITURE",
                            PositionInHierarchy = 1
                        });
                });

            modelBuilder.Entity("JewelleryApp.Models.Jewellery.AccountHead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("AccountGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BalanceType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OpeningBalance")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("AccountGroupId");

                    b.ToTable("AccountHeads");
                });

            modelBuilder.Entity("JewelleryApp.Models.Jewellery.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<int>("BalanceType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GoldBalanceType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mobile")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OpeningBalance")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OpeningGold")
                        .HasColumnType("decimal(10, 3)");

                    b.Property<decimal>("OpeningSilver")
                        .HasColumnType("decimal(10, 3)");

                    b.Property<int>("SilverBalanceType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StateCode")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("JewelleryApp.Models.Jewellery.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CGST")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("GoldValueTotal")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("GstRate")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("IGST")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("InvoiceNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MakingChargesTotal")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("MetalReceivedFineWeight")
                        .HasColumnType("decimal(10, 3)");

                    b.Property<decimal>("MetalReceivedPurity")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("MetalReceivedType")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MetalReceivedWeight")
                        .HasColumnType("decimal(10, 3)");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("PaymentMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PrintOption")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Remarks")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RoundedOff")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("SGST")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("JewelleryApp.Models.Jewellery.InvoiceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("FineWt")
                        .HasColumnType("decimal(10, 3)");

                    b.Property<decimal>("GrossWt")
                        .HasColumnType("decimal(10, 3)");

                    b.Property<string>("HUID")
                        .HasColumnType("TEXT");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MakingCharges")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("MakingPercent")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("Metal")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MetalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("NetWt")
                        .HasColumnType("decimal(10, 3)");

                    b.Property<string>("Purity")
                        .HasColumnType("TEXT");

                    b.Property<string>("RI")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("InvoiceItems");
                });

            modelBuilder.Entity("JewelleryApp.Models.Jewellery.ItemMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DefaultRate")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OpeningStock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Purity")
                        .HasColumnType("TEXT");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalWeight")
                        .HasColumnType("decimal(18, 3)");

                    b.HasKey("Id");

                    b.ToTable("ItemsMaster");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Gold",
                            CreatedAt = new DateTime(2026, 4, 27, 11, 40, 2, 661, DateTimeKind.Local).AddTicks(4796),
                            DefaultRate = 0m,
                            Name = "Gold Ring",
                            OpeningStock = 0,
                            Purity = "22K",
                            StockQuantity = 0,
                            TotalWeight = 0m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Gold",
                            CreatedAt = new DateTime(2026, 4, 27, 11, 40, 2, 662, DateTimeKind.Local).AddTicks(3240),
                            DefaultRate = 0m,
                            Name = "Gold Chain",
                            OpeningStock = 0,
                            Purity = "22K",
                            StockQuantity = 0,
                            TotalWeight = 0m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Gold",
                            CreatedAt = new DateTime(2026, 4, 27, 11, 40, 2, 662, DateTimeKind.Local).AddTicks(3255),
                            DefaultRate = 0m,
                            Name = "Gold Bangle",
                            OpeningStock = 0,
                            Purity = "22K",
                            StockQuantity = 0,
                            TotalWeight = 0m
                        },
                        new
                        {
                            Id = 4,
                            Category = "Gold",
                            CreatedAt = new DateTime(2026, 4, 27, 11, 40, 2, 662, DateTimeKind.Local).AddTicks(3257),
                            DefaultRate = 0m,
                            Name = "Gold Necklace",
                            OpeningStock = 0,
                            Purity = "22K",
                            StockQuantity = 0,
                            TotalWeight = 0m
                        },
                        new
                        {
                            Id = 5,
                            Category = "Gold",
                            CreatedAt = new DateTime(2026, 4, 27, 11, 40, 2, 662, DateTimeKind.Local).AddTicks(3280),
                            DefaultRate = 0m,
                            Name = "Gold Earrings",
                            OpeningStock = 0,
                            Purity = "22K",
                            StockQuantity = 0,
                            TotalWeight = 0m
                        },
                        new
                        {
                            Id = 6,
                            Category = "Gold",
                            CreatedAt = new DateTime(2026, 4, 27, 11, 40, 2, 662, DateTimeKind.Local).AddTicks(3282),
                            DefaultRate = 0m,
                            Name = "Gold Pendant",
                            OpeningStock = 0,
                            Purity = "22K",
                            StockQuantity = 0,
                            TotalWeight = 0m
                        },
                        new
                        {
                            Id = 7,
                            Category = "Gold",
                            CreatedAt = new DateTime(2026, 4, 27, 11, 40, 2, 662, DateTimeKind.Local).AddTicks(3283),
                            DefaultRate = 0m,
                            Name = "Gold Mangalsutra",
                            OpeningStock = 0,
                            Purity = "22K",
                            StockQuantity = 0,
                            TotalWeight = 0m
                        },
                        new
                        {
                            Id = 8,
                            Category = "Gold",
                            CreatedAt = new DateTime(2026, 4, 27, 11, 40, 2, 662, DateTimeKind.Local).AddTicks(3284),
                            DefaultRate = 0m,
                            Name = "Gold Nose Pin",
                            OpeningStock = 0,
                            Purity = "22K",
                            StockQuantity = 0,
                            TotalWeight = 0m
                        },
                        new
                        {
                            Id = 9,
                            Category = "Gold",
                            CreatedAt = new DateTime(2026, 4, 27, 11, 40, 2, 662, DateTimeKind.Local).AddTicks(3286),
                            DefaultRate = 0m,
                            Name = "Gold Bracelet",
                            OpeningStock = 0,
                            Purity = "22K",
                            StockQuantity = 0,
                            TotalWeight = 0m
                        },
                        new
                        {
                            Id = 10,
                            Category = "Silver",
                            CreatedAt = new DateTime(2026, 4, 27, 11, 40, 2, 662, DateTimeKind.Local).AddTicks(3287),
                            DefaultRate = 0m,
                            Name = "Silver Payal (Anklet)",
                            OpeningStock = 0,
                            Purity = "70%",
                            StockQuantity = 0,
                            TotalWeight = 0m
                        },
                        new
                        {
                            Id = 11,
                            Category = "Silver",
                            CreatedAt = new DateTime(2026, 4, 27, 11, 40, 2, 662, DateTimeKind.Local).AddTicks(3288),
                            DefaultRate = 0m,
                            Name = "Silver Bichiya (Toe Ring)",
                            OpeningStock = 0,
                            Purity = "70%",
                            StockQuantity = 0,
                            TotalWeight = 0m
                        },
                        new
                        {
                            Id = 12,
                            Category = "Silver",
                            CreatedAt = new DateTime(2026, 4, 27, 11, 40, 2, 662, DateTimeKind.Local).AddTicks(3290),
                            DefaultRate = 0m,
                            Name = "Silver Coin",
                            OpeningStock = 0,
                            Purity = "99%",
                            StockQuantity = 0,
                            TotalWeight = 0m
                        },
                        new
                        {
                            Id = 13,
                            Category = "Silver",
                            CreatedAt = new DateTime(2026, 4, 27, 11, 40, 2, 662, DateTimeKind.Local).AddTicks(3291),
                            DefaultRate = 0m,
                            Name = "Silver Glass",
                            OpeningStock = 0,
                            Purity = "80%",
                            StockQuantity = 0,
                            TotalWeight = 0m
                        },
                        new
                        {
                            Id = 14,
                            Category = "Silver",
                            CreatedAt = new DateTime(2026, 4, 27, 11, 40, 2, 662, DateTimeKind.Local).AddTicks(3292),
                            DefaultRate = 0m,
                            Name = "Silver Spoon",
                            OpeningStock = 0,
                            Purity = "80%",
                            StockQuantity = 0,
                            TotalWeight = 0m
                        },
                        new
                        {
                            Id = 15,
                            Category = "Silver",
                            CreatedAt = new DateTime(2026, 4, 27, 11, 40, 2, 662, DateTimeKind.Local).AddTicks(3294),
                            DefaultRate = 0m,
                            Name = "Silver Idol",
                            OpeningStock = 0,
                            Purity = "80%",
                            StockQuantity = 0,
                            TotalWeight = 0m
                        },
                        new
                        {
                            Id = 16,
                            Category = "Silver",
                            CreatedAt = new DateTime(2026, 4, 27, 11, 40, 2, 662, DateTimeKind.Local).AddTicks(3295),
                            DefaultRate = 0m,
                            Name = "Silver Chain",
                            OpeningStock = 0,
                            Purity = "70%",
                            StockQuantity = 0,
                            TotalWeight = 0m
                        },
                        new
                        {
                            Id = 17,
                            Category = "Silver",
                            CreatedAt = new DateTime(2026, 4, 27, 11, 40, 2, 662, DateTimeKind.Local).AddTicks(3296),
                            DefaultRate = 0m,
                            Name = "Silver Bracelet",
                            OpeningStock = 0,
                            Purity = "70%",
                            StockQuantity = 0,
                            TotalWeight = 0m
                        },
                        new
                        {
                            Id = 18,
                            Category = "Silver",
                            CreatedAt = new DateTime(2026, 4, 27, 11, 40, 2, 662, DateTimeKind.Local).AddTicks(3297),
                            DefaultRate = 0m,
                            Name = "Silver Ring",
                            OpeningStock = 0,
                            Purity = "70%",
                            StockQuantity = 0,
                            TotalWeight = 0m
                        });
                });

            modelBuilder.Entity("JewelleryApp.Models.Jewellery.ShopSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountNo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ActivationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address2")
                        .HasColumnType("TEXT");

                    b.Property<string>("BankBranch")
                        .HasColumnType("TEXT");

                    b.Property<string>("BankName")
                        .HasColumnType("TEXT");

                    b.Property<string>("CityState")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DefaultGoldRate")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("DefaultMakingPercent")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("DefaultSilverMakingRatePerKg")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("DefaultSilverRate")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("ExpiryDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GSTIN")
                        .HasColumnType("TEXT");

                    b.Property<string>("IFSCCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastKnownMachineId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LicenseKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("MakingChargeType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PAN")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone2")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShopName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ShowFineWtColumn")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowMakingAmountColumn")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowMakingPercentColumn")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowMetalAmountColumn")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowMetalColumn")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowPurityColumn")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowRateColumn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StateCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tagline")
                        .HasColumnType("TEXT");

                    b.Property<bool>("UsePurity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ShopSettings");
                });

            modelBuilder.Entity("JewelleryApp.Models.Jewellery.StockEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemMasterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReferenceNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Remarks")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18, 3)");

                    b.HasKey("Id");

                    b.HasIndex("ItemMasterId");

                    b.ToTable("StockEntries");
                });

            modelBuilder.Entity("JewelleryApp.Models.Jewellery.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("JewelleryApp.Models.Jewellery.Voucher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FineWeight")
                        .HasColumnType("decimal(10, 3)");

                    b.Property<string>("Metal")
                        .HasColumnType("TEXT");

                    b.Property<string>("Particulars")
                        .HasColumnType("TEXT");

                    b.Property<string>("Purity")
                        .HasColumnType("TEXT");

                    b.Property<string>("Remarks")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TodayRate")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VoucherNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(10, 3)");

                    b.HasKey("Id");

                    b.ToTable("Vouchers");
                });

            modelBuilder.Entity("JewelleryApp.Models.Jewellery.VoucherItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AccountHeadId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Credit")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Debit")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Particulars")
                        .HasColumnType("TEXT");

                    b.Property<int>("VoucherId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountHeadId");

                    b.HasIndex("VoucherId");

                    b.ToTable("VoucherItems");
                });

            modelBuilder.Entity("JewelleryApp.Models.Jewellery.AccountGroup", b =>
                {
                    b.HasOne("JewelleryApp.Models.Jewellery.AccountGroup", "ParentGroup")
                        .WithMany("SubGroups")
                        .HasForeignKey("ParentGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentGroup");
                });

            modelBuilder.Entity("JewelleryApp.Models.Jewellery.AccountHead", b =>
                {
                    b.HasOne("JewelleryApp.Models.Jewellery.AccountGroup", "AccountGroup")
                        .WithMany()
                        .HasForeignKey("AccountGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountGroup");
                });

            modelBuilder.Entity("JewelleryApp.Models.Jewellery.Invoice", b =>
                {
                    b.HasOne("JewelleryApp.Models.Jewellery.Customer", "Customer")
                        .WithMany("Invoices")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("JewelleryApp.Models.Jewellery.InvoiceItem", b =>
                {
                    b.HasOne("JewelleryApp.Models.Jewellery.Invoice", "Invoice")
                        .WithMany("Items")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("JewelleryApp.Models.Jewellery.StockEntry", b =>
                {
                    b.HasOne("JewelleryApp.Models.Jewellery.ItemMaster", "Item")
                        .WithMany()
                        .HasForeignKey("ItemMasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("JewelleryApp.Models.Jewellery.VoucherItem", b =>
                {
                    b.HasOne("JewelleryApp.Models.Jewellery.AccountHead", "AccountHead")
                        .WithMany()
                        .HasForeignKey("AccountHeadId");

                    b.HasOne("JewelleryApp.Models.Jewellery.Voucher", "Voucher")
                        .WithMany("Items")
                        .HasForeignKey("VoucherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountHead");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("JewelleryApp.Models.Jewellery.AccountGroup", b =>
                {
                    b.Navigation("SubGroups");
                });

            modelBuilder.Entity("JewelleryApp.Models.Jewellery.Customer", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("JewelleryApp.Models.Jewellery.Invoice", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("JewelleryApp.Models.Jewellery.Voucher", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
